### ISSUE TITLE
Inconsistency between Scaling Rules Configuration and Environment Variables ':' char should be replaced by '__'

### ISSUE THREAD

**Issue by AlexMasson** [Azure/azure-functions-on-container-apps#63]
**Which trigger/binding are you using?**
- ServiceBusTrigger

**Which language are you using?**
C#

**Expected behavior**
The scaling rule must work.

**Actual behavior**
I have an Azure Function with a ServiceBusTrigger. The trigger is configured according to the documentation, with environment variables containing the ":" character in the name to hierarchize the app settings.

`[ServiceBusTrigger("%ImagoSdk:ServiceBus:Topics:InternalBigData%", Connection = "ImagoSdk:ServiceBus:ConnectionString", IsSessionsEnabled = true)]`

The app settings are registered as environment variables in the Azure Function using "__" instead of ":" for Linux compatibility.

![image](https://github.com/Azure/azure-functions-on-container-apps/assets/9590747/e5965121-878d-40c2-aa3a-206e0b1cf4a3)

When the function is deployed in an Azure Function on Container App, the scaling rule uses the app settings name with ":", thus it doesn't work.

![image](https://github.com/Azure/azure-functions-on-container-apps/assets/9590747/9a066aed-10b7-48bc-a712-9fff789fe8cd)

Additionally, when a scaling rule does not work, the ContainerApp remains up 24/7, which can be problematic if unnoticed, as it prevents stopping, starting, or restarting the Azure Function.

**To Reproduce**

- Create a basic Azure Function in C#, .NET8 in an Isolated Process.
- Add a ServiceBusTrigger configured with an app setting containing the ":" char.
- Deploy it to an Azure Function on ContainerApp.
- Notice that the scaling rule does not use the correct naming convention.

**Logs**
Here are some SystemLogs from the ContainerApp

```
error parsing azure service bus metadata: no connection setting given
```

**Comment by raorugan** [comment]
hi @AlexMasson , can you please let us know how did you create this function app and what command did you use to create?

**Comment by AlexMasson** [comment]
Hi @raorugan, here is a zip file containing :
- A bicep file to deploy the managed environment, service bus + queue, storage account, functionapp. The function app use an image I just deployed to Docker Hub, which is an Azure Function containing a ServiceBusTrigger.
- The source code of the image.

The bicep file was deployed using this CLI command :
`az deployment group create --resource-group xxx --template-file function-aca.bicep`

I didn't create a Log Analytics Workspace for this example, but you'll have to if you want to get this trace in system logs of the container app :
`error parsing azure service bus metadata: no connection setting given`

This exemple display a function app which never scale down, because the scaling rule is not working.

[ContainerAppIssue.zip](https://github.com/user-attachments/files/16081239/ContainerAppIssue.zip)

**Comment by krishnajaju** [comment]
Thanks for all the details, @AlexMasson. Can you please try wrapping the Connection setting name in double percent signs (%%) and let us know if scaling works as expected?

`[ServiceBusTrigger("%ImagoSdk:ServiceBus:Topics:InternalBigData%", Connection = "%ImagoSdk:ServiceBus:ConnectionString%", IsSessionsEnabled = true)]`

**Comment by AlexMasson** [comment]
Hello @krishnajaju , thank you for your response.

I tried this solution:

- The Azure Function is no longer working at all because the ConnectionString value of the ServiceBusTrigger attribute must not be set inside double percent signs, according to the [official documentation](https://learn.microsoft.com/en-us/azure/azure-functions/functions-bindings-service-bus-trigger?tabs=python-v2%2Cisolated-process%2Cnodejs-v4%2Cextensionv5&pivots=programming-language-csharp#example). The error when I tried to debug with it:
`The listener for function 'XXX' was unable to start. Microsoft.Azure.WebJobs.Extensions.ServiceBus: Service Bus account connection string 'Endpoint=sb://XXX.servicebus.windows.net/;SharedAccessKeyName=RootManageSharedAccessKey;SharedAccessKey=XXX' does not exist. Make sure that it is a defined App Setting.`

- The scaling rule is also not working. With this solution, the value of the scaling rule parameter "connectionFromEnv" is replaced by the value of the connection string. This value must be the name of the environment variable containing the connection string, according to the [Keda documentation](https://keda.sh/docs/2.14/scalers/azure-service-bus/#trigger-specification).

**Comment by krishnajaju** [comment]
Thanks for trying it out @AlexMasson and apologies it did not resolve the issue. We have identified a bug in our system, and we will work on fixing this soon. As a temporary work-around, I would suggest having two app settings for service bus connection string, one with delimiter `:` and another with delimiter `__` pointing to the same ServiceBus connection string, until we fix this issue. Please let me know if this workaround helps. We will let you know once fix for this issue is rolled out.

**Comment by AlexMasson** [comment]
Ok thank you @krishnajaju I will do that.
Keep me informed.

**Comment by AlexMasson** [comment]
Hello @krishnajaju , this work-around is unfortunately not working, I have this kind of error during the deployment :
`Env variable name 'xx:xx:xx' contains invalid character, regex used for validation is '^[-._a-zA-Z][-._a-zA-Z0-9]*$'`

**Comment by krishnajaju** [comment]
Thanks for trying it out @AlexMasson. We are currently working on fixing this bug, and we will update you once the fix is rolled out. Until then, can you please reference app settings for `Connection` attribute without any hierarchy (without any `:` or `__`)?

**Comment by krishnajaju** [comment]
Hi @AlexMasson, the bug has been fixed and the update has been rolled out. Please let us know if you encounter any further issues.
